### ISSUE TITLE
Merge with gortc/stun

### ISSUE THREAD

**Issue by ernado** [pion/stun#10]
So we've decided to merge with [gortc/stun](https://github.com/gortc/stun) and release it as stun/v2.

This is a tracking issue for that process.

- [x] ICE PR https://github.com/pion/ice/pull/44
- [x] TURN PR (TODO)
- [x] WebRTC PR https://github.com/pion/webrtc/pull/682

**Comment by Sean-Der** [comment]
That ICE PR is fantastic, nice work @ernado! Really glad we can move the auth stuff into `stun` pkg itself.

I would also open up a PR against `pion/webrtc` using the new STUN branch. It might reveal issues (or just give higher confidence everything is working!)

**Comment by Sean-Der** [comment]
landed, nice work @ernado 🎊

**Comment by Sean-Der** [comment]
Just finished merging `pion/turn`

@ernado When you are free lets talk next steps!
