### ISSUE TITLE
README.md outdated. go get is now used differently

### ISSUE THREAD

**Issue by yjeanrenaud** [pion/stun#121]
### What did you do?
`go get github.com/pion/stun/tree/master/cmd/stun-nat-behaviour`

### What did you expect?
installing stun-nat-behaviour

### What happened?
got error.

used `go install github.com/pion/stun/tree/master/cmd/stun-nat-behaviour@latest` and it worked

**Comment by fritzmg** [comment]
Has this changed again? I am getting

```
go: github.com/pion/stun/tree/master/cmd/stun-nat-behaviour@latest: module github.com/pion/stun@latest found (v0.3.5), but does not contain package github.com/pion/stun/tree/master/cmd/stun-nat-behaviour
```

an nothing will be installed in `$GOPATH` afterwards.

**Comment by SubOptimal** [comment]
@yjeanrenaud This change is addressed by PR #119.

**Comment by ashellunts** [comment]
Fix is merged to master.

**Comment by Weltolk** [comment]
> Has this changed again? I am getting
> 
> ```
> go: github.com/pion/stun/tree/master/cmd/stun-nat-behaviour@latest: module github.com/pion/stun@latest found (v0.3.5), but does not contain package github.com/pion/stun/tree/master/cmd/stun-nat-behaviour
> ```
> 
> an nothing will be installed in `$GOPATH` afterwards.

same issue

**Comment by Sean-Der** [comment]
@Weltolk What command are you running? Where did you get the command from?

**Comment by Weltolk** [comment]
> @Weltolk What command are you running? Where did you get the command from?

https://github.com/pion/stun/blob/master/cmd/stun-nat-behaviour/README.md

`Linux server0 5.10.0-25-arm64 #1 SMP Debian 5.10.191-1 (2023-08-16) aarch64 GNU/Linux`

`go version go1.21.1 linux/arm64`

`go install github.com/pion/stun/v2/cmd/stun-nat-behaviour@latest`

`
go: github.com/pion/stun/cmd/stun-nat-behavior@latest: module github.com/pion/stun@latest found (v0.6.1), but does not contain package github.com/pion/stun/cmd/stun-nat-behavior
`

**Comment by Weltolk** [comment]
> @Weltolk What command are you running? Where did you get the command from?

I try the new commit, but same

`go install github.com/pion/stun/v2/cmd/stun-nat-behaviour@latest`

```
go install github.com/pion/stun/v2/cmd/stun-nat-behavior@latest
```

**Comment by Sean-Der** [comment]
@Weltolk I am having a hard time reproducing this :/

```
$ docker run -it debian:sid /bin/bash

$ apt update && apt install golang ca-certificates

$ go version
go version go1.21.1 linux/amd64

$ go install github.com/pion/stun/v2/cmd/stun-nat-behaviour@latest
go: downloading github.com/pion/stun v0.6.1
go: downloading github.com/pion/stun/v2 v2.0.0
go: downloading github.com/pion/logging v0.2.2
go: downloading github.com/pion/dtls/v2 v2.2.7
go: downloading github.com/pion/transport/v3 v3.0.1
go: downloading github.com/pion/transport/v2 v2.2.1
go: downloading golang.org/x/crypto v0.12.0

$ ~/go/bin/stun-nat-behaviour
```

**Comment by Weltolk** [comment]
> @Weltolk I am having a hard time reproducing this :/
> 
> ```
> $ docker run -it debian:sid /bin/bash
> 
> $ apt update && apt install golang ca-certificates
> 
> $ go version
> go version go1.21.1 linux/amd64
> 
> $ go install github.com/pion/stun/v2/cmd/stun-nat-behaviour@latest
> go: downloading github.com/pion/stun v0.6.1
> go: downloading github.com/pion/stun/v2 v2.0.0
> go: downloading github.com/pion/logging v0.2.2
> go: downloading github.com/pion/dtls/v2 v2.2.7
> go: downloading github.com/pion/transport/v3 v3.0.1
> go: downloading github.com/pion/transport/v2 v2.2.1
> go: downloading golang.org/x/crypto v0.12.0
> 
> $ ~/go/bin/stun-nat-behaviour
> ```

I don't know why, amd64 ubuntu have same issue

```
┌──(root㉿server1)-[~]
└─# uname -a
Linux server1 5.15.0-1040-oracle #46-Ubuntu SMP Fri Jul 14 21:47:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
┌──(root㉿server1)-[~]
└─# go version
go version go1.21.1 linux/amd64
┌──(root㉿server1)-[~]
└─# go install github.com/pion/stun/v2/cmd/stun-nat-behavior@latest
go: github.com/pion/stun/v2/cmd/stun-nat-behavior@latest: module github.com/pion/stun/v2@latest found (v2.0.0), but does not contain package github.com/pion/stun/v2/cmd/stun-nat-behavior
┌──(root㉿server1)-[~]
└─# echo $GOPATH

┌──(root㉿server1)-[~]
└─# ll ~/go
total 4
drwxr-xr-x 4 root root 4096 Sep 24 16:39 pkg

┌──(root㉿server1)-[~]
└─# go install github.com/pion/stun/cmd/stun-nat-behavior@latest
go: github.com/pion/stun/cmd/stun-nat-behavior@latest: module github.com/pion/stun@latest found (v0.6.1), but does not contain package github.com/pion/stun/cmd/stun-nat-behavior
┌──(root㉿server1)-[~]
└─# ll ~/go
total 4
drwxr-xr-x 4 root root 4096 Sep 24 16:39 pkg
```

**Comment by Sean-Der** [comment]
I see the issue! Typo in the `go install`. You are missing a `u` in 

* `go install github.com/pion/stun/v2/cmd/stun-nat-behaviour@latest`
* `go install github.com/pion/stun/v2/cmd/stun-nat-behavior@latest`

**Comment by Weltolk** [comment]
> I see the issue! Typo in the `go install`. You are missing a `u` in 
> 
> * `go install github.com/pion/stun/v2/cmd/stun-nat-behaviour@latest`
> * `go install github.com/pion/stun/v2/cmd/stun-nat-behavior@latest`
> 

OMG! I am so sry
