### ISSUE TITLE
stun-nat-behaviour: command not found

### ISSUE THREAD

**Issue by David-dp-** [pion/stun#40]
### Your environment.
Welcome to Ubuntu 20.04.1 LTS (GNU/Linux 4.19.104-microsoft-standard x86_64)

### What did you do?
Followed README at https://github.com/pion/stun/tree/master/cmd/stun-nat-behaviour

$ sudo apt install golang-go  # version 2:1.13~1ubuntu2
$ go get github.com/pion/stun/cmd/stun-nat-behaviour
$ go
Go is a tool for managing Go source code.

$ stun-nat-behaviour
stun-nat-behaviour: command not found

### What did you expect?
A usage string from stun-nat-behaviour, because "[options]" aren't expanded and explained in the README

### What happened?
stun-nat-behaviour couldn't be executed...seemingly because no working copy was downloaded:

$ ls -l
total 4
drwxr-xr-x 4 david david 4096 Aug 13 14:42 go

$ ls -l go
total 8
drwxr-xr-x 2 david david 4096 Aug 13 14:42 bin
drwxr-xr-x 3 david david 4096 Aug 13 14:42 src

**Comment by Sean-Der** [comment]
Hey @David-dp- 

I think this will be in your `bin` folder. If that doesn't work you download the repo and run `go build` directly in it.

If that works a doc update would really be appreciated!

**Comment by Sean-Der** [comment]
Fixed by #41 

@David-dp- So one thing to note is that that tool will never interact with TURN. If you want a CLI TURN client you could use [pion/turn](https://github.com/pion/turn/tree/master/examples/turn-client) !

TURN really solves another class of problems and doesn't care about NATs.
